language: node_js

node_js:
  - 'stable'

sudo: false

env:
  - workerCount=3

matrix:
  fast_finish: true

install:
  - npm install

script:
  - npm run build

cache:
  directories:
    - node_modules

git:
  depth: 1