language: node_js

node_js:
  - "lts/*"

sudo: false

matrix:
  fast_finish: true

script:
  - npm run bootstrap
  - npm run build
  - npm test
  - npm run docs

after_success:
  - "./node_modules/.bin/codecov -f ./build/coverage/*.json"

cache:
  directories:
    - node_modules

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "Brian.Ingenito@morganstanley.com"
    api_key: $NPMJS_TOKEN # Set in travis-ci.org dashboard
    on:
      tags: true
      branch: master