language: node_js

node_js:
  - 'stable'

sudo: false

matrix:
  fast_finish: true

script:
  - npm run build

after_success:
  - "./node_modules/.bin/codecov -f ./build/coverage/*.json"

cache:
  directories:
    - node_modules
