language: node_js

node_js:
  - 'stable'

sudo: false

matrix:
  fast_finish: true

script:
  - npm run build

after_success:
  - "cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

cache:
  directories:
    - node_modules
